import mongoose from 'mongoose';
import MaterialMaster from '../models/MaterialMaster';
import { ensureConnection } from '../db/connection';

const sampleMaterials = [
    {
        material_id: "RM001",
        material_name: "Spunlace Nonwoven Fabric (65mm)",
        material_short_name: "Fabric (65mm)",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM002",
        material_name: "Duvet Flexible Laminate",
        material_short_name: "Duvet Laminate",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM001",
        material_name: "Duvet Packing Carton - 24 pack",
        material_short_name: "Duvet 24s Pack",
        uom: "NOS",
        material_category_id: "M02",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 100000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM002",
        material_name: "Duvet Packing Carton - 12 pack",
        material_short_name: "Duvet 12s Pack",
        uom: "NOS",
        material_category_id: "M02",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 100000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM003",
        material_name: "Duvet Packing Carton - 6 pack",
        material_short_name: "Duvet 6s Pack",
        uom: "NOS",
        material_category_id: "M02",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 100000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM004",
        material_name: "Sterilization Carton - Duvet",
        material_short_name: "Duvet Steri Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: null, // "??" represented as null
        lead_time_days_max: null, // "??" represented as null
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM005",
        material_name: "Shipper Carton - Duvet",
        material_short_name: "Duvet Shipper Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: 7,
        lead_time_days_max: 10,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM003",
        material_name: "Spunlace Nonwoven Fabric (120mm) for XL",
        material_short_name: "Fabric (120mm) for XL",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM004",
        material_name: "Duvet XL Flexible Laminate",
        material_short_name: "Duvet XL Laminate",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM006",
        material_name: "Duvet XL Packing Carton - 24 pack",
        material_short_name: "Duvet XL 24s Pack",
        uom: "NOS",
        material_category_id: "M02",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 100000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM007",
        material_name: "Sterilization Carton - Duvet XL",
        material_short_name: "Duvet XL Steri Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: null, // "??" represented as null
        lead_time_days_max: null, // "??" represented as null
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM008",
        material_name: "Shipper Carton - Duvet XL",
        material_short_name: "Duvet XL Shipper Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: 7,
        lead_time_days_max: 10,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM005",
        material_name: "Spunlace Nonwoven Fabric (200mm) for Ultra",
        material_short_name: "Fabric (200mm) for Ultra",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM006",
        material_name: "Duvet Ultra Flexible Laminate",
        material_short_name: "Duvet Ultra Laminate",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM009",
        material_name: "Duvet Ultra Packing Carton - 6s pack",
        material_short_name: "Duvet Ultra 6s Pack",
        uom: "NOS",
        material_category_id: "M02",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 100000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM010",
        material_name: "Sterilization Carton - Duvet Ultra",
        material_short_name: "Duvet Ultra Steri Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: null, // "??" represented as null
        lead_time_days_max: null, // "??" represented as null
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM011",
        material_name: "Shipper Carton - Duvet Ultra",
        material_short_name: "Duvet Ultra Shipper Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: 7,
        lead_time_days_max: 10,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "RM007",
        material_name: "Nanai Flexible Laminate",
        material_short_name: "Nanai Laminate",
        uom: "KGS",
        material_category_id: "M01",
        material_type: "RM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 1000,
        lead_time_days_min: 25,
        lead_time_days_max: 40,
        shelf_life_in_months: 12,
        qc_required: true,
        coa_checklist_id: "CL02",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
    {
        material_id: "PM012",
        material_name: "Nanai Shipper Carton",
        material_short_name: "Nanai Shipper Carton",
        uom: "NOS",
        material_category_id: "M03",
        material_type: "PM",
        material_spec: "",
        safety_stock_qty: undefined,
        re_order_qty: undefined,
        min_order_qty: 25000,
        lead_time_days_min: 7,
        lead_time_days_max: 10,
        shelf_life_in_months: 12,
        qc_required: false,
        coa_checklist_id: "",
        material_image: "",
        material_image_icon: "",
        active: true,
    },
];

async function seedMaterials() {
    try {
        await ensureConnection();
        console.log('Connected to database');

        for (const materialData of sampleMaterials) {
            const material = await MaterialMaster.findOneAndUpdate(
                { material_id: materialData.material_id },
                {
                    ...materialData,
                    last_modified_user_id: 'ADMIN',
                    last_modified_date_time: new Date(),
                },
                { upsert: true, new: true, runValidators: true }
            );
            console.log(`Material ${material.material_id} - ${material.material_name} added/updated`);
        }

        console.log('All materials seeded successfully');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding materials:', error);
        process.exit(1);
    }
}

seedMaterials();












